# Generated by Django 3.1.3 on 2022-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220526_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_number',
            field=models.TextField(default='101', max_length=5),
        ),
    ]
