# Generated by Django 3.1.3 on 2022-05-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_question_q_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_number',
        ),
    ]
